#!/bin/bash
mkdir proj
cd proj
cmake ../ -DNATIVECORD_LIB_TEST=ON -DLWS_WITH_MINIMAL_EXAMPLES=OFF -DLWS_WITHOUT_SERVER=OFF -DLWS_UNIX_SOCK=OFF -DLWS_WITH_HTTP_DIGEST_AUTH=OFF -DLWS_CTEST_INTERNET_AVAILABLE=OFF
cd ..
