#pragma once

/*
    https://github.com/discord/discord-api-docs/blob/main/docs/topics/Opcodes_and_Status_Codes.md
*/

enum GatewayCode
{
    GATEWAY_INVALID = -1,
    GATEWAY_DISPATCH = 0,
    GATEWAY_HEARTBEAT = 1,
    GATEWAY_IDENTIFY = 2,
    GATEWAY_PRESENCE_UPDATE = 3,
    GATEWAY_VOICE_STATE_UPDATE = 4,
    GATEWAY_RESUME = 6,
    GATEWAY_RECONNECT = 7,
    GATEWAY_REQUEST_GUILD_MEMBERS = 8,
    GATEWAY_INVALID_SESSION = 9,
    GATEWAY_HELLO = 10,
    GATEWAY_HEARTBEAT_ACK = 11
};

enum GatewayCloseCode
{
    CLOSE_UNKNOWN_ERROR = 4000,
    CLOSE_UNKNOWN_OPCODE = 4001,
    CLOSE_DECODE_ERROR = 4002,
    CLOSE_NOT_AUTHENTICATED = 4003,
    CLOSE_AUTHENTICATION_FAILED = 4004,
    CLOSE_ALREADY_AUTHENTICATED = 4005,
    CLOSE_INVALID_SEQ = 4007,
    CLOSE_RATE_LIMITED = 4008,
    CLOSE_SESSION_TIMED_OUT = 4009,
    CLOSE_INVALID_SHARD = 4010,
    CLOSE_SHARDING_REQUIRED = 4011,
    CLOSE_INVALID_API_VERSION = 4012,
    CLOSE_INVALID_INTENTS = 4013,
    CLOSE_DISALLOWED_INTENTS = 4014
};

enum GatewayVoiceCode
{
    VOICE_IDENTIFY = 0,
    VOICE_SELECT_PROTOCOL = 1,
    VOICE_READY = 2,
    VOICE_HEARTBEAT = 3,
    VOICE_SESSION_DESCRIPTION = 4,
    VOICE_SPEAKING = 5,
    VOICE_HEARTBEAT_ACK = 6,
    VOICE_RESUME = 7,
    VOICE_HELLO = 8,
    VOICE_RESUMED = 9,
    VOICE_CLIENT_DISCONNECT = 13
};

enum VoiceCloseCode {
    VOICE_CLOSE_UNKNOWN_OPCODE = 4001,
    VOICE_CLOSE_FAILED_TO_DECODE_PAYLOAD = 4002,
    VOICE_CLOSE_NOT_AUTHENTICATED = 4003,
    VOICE_CLOSE_AUTHENTICATION_FAILED = 4004,
    VOICE_CLOSE_ALREADY_AUTHENTICATED = 4005,
    VOICE_CLOSE_SESSION_NO_LONGER_VALID = 4006,
    VOICE_CLOSE_SESSION_TIMEOUT = 4009,
    VOICE_CLOSE_SERVER_NOT_FOUND = 4011,
    VOICE_CLOSE_UNKNOWN_PROTOCOL = 4012,
    VOICE_CLOSE_DISCONNECTED = 4014,
    VOICE_CLOSE_VOICE_SERVER_CRASHED = 4015,
    VOICE_CLOSE_UNKNOWN_ENCRYPTION_MODE = 4016
};
